# version: 2.1
# parameters:
#   job:
#     type: string
#     default: "ebuild"
#   GHA_Actor:
#     type: string
#     default: ""
#   GHA_Action:
#     type: string
#     default: ""
#   GHA_Event:
#     type: string
#     default: ""
#   GHA_Meta:
#     type: string
#     default: ""
#   payload:
#     type: string
#     default: "None"
#   action:
#     type: string
#     default: "Plzz"
    
# pull: &pull
#   filters:
#     branches:
#       only:
#         - dev
#         - /^pull\/[\d]*$/
#         - main

# # Define the jobs we want to run for this project
# jobs:
#   build:
#     docker:
#       - image: cimg/base:2023.03
#     steps:
#       - checkout
#       - run: echo "this is the build job"
#       - run: echo "Source of trigger is << pipeline.parameters.GHA_Event >>"
#       - run: echo "required value << pipeline.parameters.action >>"
      
#   destroy:
#     docker:
#       - image: cimg/base:2023.03
#     steps:
#       - checkout
#       - run: echo "This is a DESTROY JOB"
#       - run: echo "required value << pipeline.parameters.GHA_Event >>"

# # Orchestrate our job run sequence
# # workflows:
# #   build:
# #     when:
# #         matches: { pattern: "ebuild", value: << pipeline.parameters.job >> }
# #     jobs:
# #       - build


# workflows:
#   build:
#     jobs:
#       - build:
#           <<: *pull
  
#   destroy:
#     when:
#         matches: { pattern: "edestroy", value: << pipeline.parameters.job >> }
#     jobs:
#       - destroy

version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: haripofficial/internal-runner
    steps:
      - run: echo "Hi I'm on a Container Runner!"
      - run: curl http://192.168.29.62:5500/
workflows:
  build-workflow:
    jobs:
      - build
