version: 2.1
parameters:
  pull_request:
    type: boolean
    default: false
    
     
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    environment:
      MSG: << pipeline.trigger_parameters.circleci.event_type >>
    steps:
      - checkout
      - run: echo "this is the build job"
      - run: echo $MSG
      - run: echo "required value << pipeline.trigger_parameters.circleci.event_type >>"
      
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: select job
          command: |
            if [[ -n "$CIRCLE_PULL_REQUEST" ]]; then
              echo "PR JOB EXCECUTED"
            else
              echo "Normal job"
              echo $CIRCLE_PULL_REQUEST
            fi
      - run: echo "this is the build job"
      - run: echo $MSG
      - run: echo "required value << pipeline.trigger_parameters.circleci.event_type >>"

# Orchestrate our job run sequence
workflows:
  build-and-deploy:
    when:
        matches: { pattern: "pull request", value: << pipeline.trigger_parameters.circleci.event_type >> }
    jobs:
      - build
  push:
    unless: << pipeline.parameters.pull_request >>
    jobs:
      - test
