version: 2.1

on:
  pull_request:
    types: [opened]
    
jobs:
  build1:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      #- checkout
      #- run: python3 main.py
      - run:
          name: Check Scripts
          command: |
            ls
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      #- checkout
      #- run: python3 main-test.py
      - run:
          name: Check Scripts
          command: |
            ls

workflows:
  build_and_test:
    jobs:
      - build1:
          filters:
            branches:
              only: main
      - test:
          requires:
            - build1
          filters:
            branches:
              only: main
