version: 2.1
parameters:
  job:
    type: string
    default: "ebuild"
  payload:
    type: string
    default: "None"
  action:
    type: string
    default: "Plzz"
    
pull: &pull
  filters:
    branches:
      only:
        - dev
        - /^pull\/[\d]*$/
        - main

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
      - run: echo "Source of trigger is << pipeline.trigger_source >>"
      - run: echo "Payload << pipeline.parameters.payload >>"
      - run: echo "required value << pipeline.action >>"
      
  destroy:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "This is a DESTROY JOB"
      - run: echo "required value << pipeline.parameters.job >>"

# Orchestrate our job run sequence
# workflows:
#   build:
#     when:
#         matches: { pattern: "ebuild", value: << pipeline.parameters.job >> }
#     jobs:
#       - build


workflows:
  build:
    jobs:
      - build:
          <<: *pull
  
  destroy:
    when:
        matches: { pattern: "edestroy", value: << pipeline.parameters.job >> }
    jobs:
      - destroy
