version: 2.1
parameters:
  job:
    type: string
    default: "ebuild"
    
     
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
      
  destroy:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "This is a DESTROY JOB"
      - run: echo "required value << pipeline.parameters.job >>"

# Orchestrate our job run sequence
workflows:
  build:
    filters:
      branches:
        only:
          - /^pull\/[\d]*$/
#     when:
#         matches: { pattern: "ebuild", value: << pipeline.parameters.job >> }
    jobs:
      - build
  
  destroy:
    when:
        matches: { pattern: "edestroy", value: << pipeline.parameters.job >> }
    jobs:
      - destroy
