on:
  pull_request:
    types: [opened, reopened, closed]
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: trigger-pipeline
        id: trigger-pipeline
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
